cShareSystems.load_pas("Grand Homie's 2v2 NS", [
    "coui://ui/mods/grandhomie/systems/theia_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/toisengard_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/overcookedpizza_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/closair_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/tundra_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/frozenoreoyoughurt_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/gsystem_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/hells_pass_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/the_reef_2v2_ns.pas",
    "coui://ui/mods/grandhomie/systems/t-_crevage_2v2_ns.pas",
	"coui://ui/mods/grandhomie/systems/lugaan_2v2_ns.pas"
]);
cShareSystems.load_pas("Grand Homie's 3v3-5v5 NS", [
    "coui://ui/mods/grandhomie/systems/teotihuacan_3v3_ns.pas",
    "coui://ui/mods/grandhomie/systems/wide_angles_3v3_ns.pas",
    "coui://ui/mods/grandhomie/systems/tyburn_3v3_ns.pas",
    "coui://ui/mods/grandhomie/systems/ayutthaya_3v3_ns.pas",
    "coui://ui/mods/grandhomie/systems/carthage_3v3_ns.pas",
	"coui://ui/mods/grandhomie/systems/hastings_3v3_ns.pas",
	"coui://ui/mods/grandhomie/systems/lune_3v3_ns.pas",
    "coui://ui/mods/grandhomie/systems/theia_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/salt_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/castillon_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/cannae_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/bosworth_field_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/bridges_map_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/prof_x4_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/screwball_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/thewall_4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/kuppa_600_5v5_ns.pas",
    "coui://ui/mods/grandhomie/systems/homies_blurs_map_5v5_ns.pas",
	"coui://ui/mods/grandhomie/systems/wadiya_no_crater.pas"
]);
cShareSystems.load_pas("Grand Homie's 12+ Players", [
    "coui://ui/mods/grandhomie/systems/sixmetry_6v6_ns.pas",
    "coui://ui/mods/grandhomie/systems/love_triangle_4v4v4_ns.pas",
    "coui://ui/mods/grandhomie/systems/battlestar_16p.pas",
    "coui://ui/mods/grandhomie/systems/lord_of_symmetry_8v8_ns.pas",
    "coui://ui/mods/grandhomie/systems/macro_aggressions_800_16_players.pas"
]);